# Generated by Django 4.2.1 on 2023-06-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShopiety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img_url',
            field=models.ImageField(upload_to='imagenesProducto'),
        ),
    ]
